export const CN_DATA_TABLE_TRIGGER = {
    // state
    ADD_ROW: 'ADD_ROW',
    ADD_CHILD_ROW: 'ADD_CHILD_ROW',
    EDIT_ROW: 'EDIT_ROW',
    EDIT_ROWS: 'EDIT_ROWS',
    CANCEL_EDIT_ROW: 'CANCEL_EDIT_ROW',
    CANCEL_EDIT_ROWS: 'CANCEL_EDIT_ROWS',
    CANCEL_NEW_ROW: 'CANCEL_ADDED_ROW',
    CANCEL_NEW_ROWS: 'CANCEL_ADDED_ROWS',
    SEARCH_ROW: 'SEARCH_ROW',
    CANCEL_SEARCH_ROW: 'CANCEL_SEARCH_ROW',
    CHANGE_ADDED_ROWS_TO_TEXT: 'CHANGE_ADDED_ROWS_TO_TEXT',
    CHANGE_EDITED_ROWS_TO_TEXT: 'CHANGE_EDITED_ROWS_TO_TEXT',
    SHOW_INVALIDATE_ADDED_ROWS: 'SHOW_INVALIDATE_ADDED_ROWS',
    SHOW_INVALIDATE_EDITED_ROWS: 'SHOW_INVALIDATE_EDITED_ROWS',

    // action
    DIALOG: 'DIALOG',
    WINDOW: 'WINDOW',
    UPLOAD: 'UPLOAD',
    DIALOG_BATCH: 'DIALOG_BATCH',
    CONFIRM: 'CONFIRM',
    CHECKED_ITEMS_IDS_CONFIRM: 'CHECKED_ITEMS_IDS_CONFIRM',
    MESSAGE: 'MESSAGE',
    LOAD_REFRESH_DATA: 'LOAD_REFRESH_DATA',
    DATA_CHECKED_STATUS_CHANGE: 'DATA_CHECKED_STATUS_CHANGE',


    // behavior
    REFRESH: 'REFRESH',
    REFRESH_AS_CHILD: 'REFRESH_AS_CHILD',
    LOAD_BY_FILTER: 'LOAD_BY_FILTER',
    HIDDEN: 'HIDDEN',
    SHOW: 'SHOW',
    EXPORT: 'EXPORT',
    IMPORT: 'IMPORT',
    DOWNLOAD: 'DOWNLOAD',
    SELECT_ROW: 'SELECT_ROW',
    SET_SELECT_ROW: 'SET_SELECT_ROW',
    CHECK_ROW: 'CHECK_ROW',

    LINK: 'LINK',
    LINK_TO: 'LINK_TO',

    // operation
    SAVE_ROW: 'SAVE_ROW',
    SAVE_ROWS: 'SAVE_ROWS',
    DELETE_CURRENT_ROW: 'DELETE_CURRENT_ROW',
    DELETE_CHECKED_ROWS: 'DELETE_CHECKED_ROWS',
    EXECUTE_CURRENT_ROW: 'EXECUTE_CURRENT_ROW',
    EXECUTE_SELECTED_ROW: 'EXECUTE_SELECTED_ROW',
    EXECUTE_CHECKED_ROWS: 'EXECUTE_CHECKED_ROWS',
    EXECUTE_CHECKED_ROWS_IDS: 'EXECUTE_CHECKED_ROWS_IDS'
}