export const CN_TOOLBAR_TRIGGER = {
    // state
    STATE_TO_TEXT: 'STATE_TO_TEXT',
    STATE_TO_EDIT: 'STATE_TO_EDIT',
    EXECUTE_NONE: 'EXECUTE_NONE',
    EXECUTE_NONE_EDIT: 'EXECUTE_NONE_EDIT',
    SET_OPERATION_DATA: 'SET_OPERATION_DATA',
    EXECUTE: 'EXECUTE'
}